// Generated by deploy.sh / deploy.ps1 from the stack outputs. Values here are placeholders.
window.TJ_CONFIG = {
  apiUrl: "https://REPLACE.execute-api.us-west-2.amazonaws.com",
  region: "us-west-2",
  userPoolId: "REPLACE",
  clientId: "REPLACE",
  cognitoDomain: "REPLACE.auth.us-west-2.amazoncognito.com"
};
