// Generated by deploy.sh / deploy.ps1 from the stack outputs. Values here are placeholders.
window.TJ_CONFIG = {
  apiUrl: "https://REPLACE.execute-api.us-east-1.amazonaws.com",
  region: "us-east-1",
  userPoolId: "REPLACE",
  clientId: "REPLACE",
  cognitoDomain: "REPLACE.auth.us-east-1.amazoncognito.com"
};
