#!/usr/bin/env bash
# Deploy or update the whole stack, then publish the front end.
# Usage: STACK=trade-journal REGION=us-west-2 ANTHROPIC_API_KEY=sk-ant-... ./deploy.sh
set -euo pipefail
cd "$(dirname "$0")"
STACK="${STACK:-trade-journal}"
REGION="${REGION:-us-west-2}"

command -v sam >/dev/null || { echo "Install the AWS SAM CLI first: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html"; exit 1; }
command -v aws >/dev/null || { echo "Install the AWS CLI v2 first."; exit 1; }

if [ ! -f samconfig.toml ]; then
  echo "First deploy: SAM will ask for a Cognito domain prefix (must be globally unique, lowercase)."
  sam deploy --guided --stack-name "$STACK" --region "$REGION" --capabilities CAPABILITY_IAM
else
  sam deploy --stack-name "$STACK" --region "$REGION"
fi

out() { aws cloudformation describe-stacks --stack-name "$STACK" --region "$REGION" --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text; }

if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
  aws secretsmanager put-secret-value --region "$REGION" --secret-id "$(out AnthropicSecretArn)" --secret-string "$ANTHROPIC_API_KEY" >/dev/null
  echo "Anthropic API key stored in Secrets Manager."
fi

cat > frontend/config.js <<CFG
// Generated by deploy.sh from stack $STACK
window.TJ_CONFIG = {
  apiUrl: "$(out ApiUrl)",
  region: "$REGION",
  userPoolId: "$(out UserPoolId)",
  clientId: "$(out UserPoolClientId)",
  cognitoDomain: "$(out CognitoDomain)"
};
CFG

aws s3 sync frontend "s3://$(out SiteBucketName)" --delete --region "$REGION"
aws cloudfront create-invalidation --distribution-id "$(out DistributionId)" --paths "/*" >/dev/null
echo
echo "Done. Open $(out SiteUrl)"
echo "(A brand-new CloudFront distribution can take a few minutes before the URL answers.)"
