# Deploy or update the whole stack, then publish the front end (Windows PowerShell).
# Usage: $env:ANTHROPIC_API_KEY="sk-ant-..."; .\deploy.ps1 -Stack trade-journal -Region us-west-2
param([string]$Stack = "trade-journal", [string]$Region = "us-west-2")
$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

if (-not (Get-Command sam -ErrorAction SilentlyContinue)) { throw "Install the AWS SAM CLI first." }
if (-not (Get-Command aws -ErrorAction SilentlyContinue)) { throw "Install the AWS CLI v2 first." }

if (-not (Test-Path samconfig.toml)) {
  Write-Host "First deploy: SAM will ask for a Cognito domain prefix (must be globally unique, lowercase)."
  sam deploy --guided --stack-name $Stack --region $Region --capabilities CAPABILITY_IAM
} else {
  sam deploy --stack-name $Stack --region $Region
}
if ($LASTEXITCODE -ne 0) { throw "sam deploy failed" }

function Out($key) { aws cloudformation describe-stacks --stack-name $Stack --region $Region --query "Stacks[0].Outputs[?OutputKey=='$key'].OutputValue" --output text }

if ($env:ANTHROPIC_API_KEY) {
  aws secretsmanager put-secret-value --region $Region --secret-id (Out "AnthropicSecretArn") --secret-string $env:ANTHROPIC_API_KEY | Out-Null
  Write-Host "Anthropic API key stored in Secrets Manager."
}

$cfg = @"
// Generated by deploy.ps1 from stack $Stack
window.TJ_CONFIG = {
  apiUrl: "$(Out 'ApiUrl')",
  region: "$Region",
  userPoolId: "$(Out 'UserPoolId')",
  clientId: "$(Out 'UserPoolClientId')",
  cognitoDomain: "$(Out 'CognitoDomain')"
};
"@
Set-Content -Path frontend/config.js -Value $cfg -Encoding UTF8

aws s3 sync frontend "s3://$(Out 'SiteBucketName')" --delete --region $Region
aws cloudfront create-invalidation --distribution-id (Out "DistributionId") --paths "/*" | Out-Null
Write-Host ""
Write-Host "Done. Open $(Out 'SiteUrl')"
Write-Host "(A brand-new CloudFront distribution can take a few minutes before the URL answers.)"
